steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/interspace-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/interspace-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'interspace-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/interspace-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000,REDIS_ENABLED=false'

images:
  - 'gcr.io/$PROJECT_ID/interspace-backend:$COMMIT_SHA'

timeout: '1200s'