steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/interspace-backend:${BUILD_ID}', '-t', 'gcr.io/$PROJECT_ID/interspace-backend:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/interspace-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'interspace-backend-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/interspace-backend:${BUILD_ID}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=development,REDIS_ENABLED=true,DUO_NODE_URL=https://interspace-duo-node-dev-e67lrclhcq-uc.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/interspace-backend:${BUILD_ID}'
  - 'gcr.io/$PROJECT_ID/interspace-backend:latest'

timeout: '1200s'