services:
  # PostgreSQL for local development
  postgres:
    image: postgres:15-alpine
    container_name: interspace-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interspace_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for distributed features (rate limiting, blacklist, caching)
  redis:
    image: redis:7-alpine
    container_name: interspace-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass devpassword
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "-a", "devpassword", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: interspace-backend-dev
    restart: unless-stopped
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/interspace_dev
      - REDIS_ENABLED=true
      - REDIS_URL=redis://:devpassword@redis:6379/0
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production
      - JWT_REFRESH_EXPIRES_IN=7d
      - ENCRYPTION_SECRET=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - LOG_EMAIL_CODES=${LOG_EMAIL_CODES:-false}
      # V2 API Settings
      - ENABLE_V2_API=true
      - AUTO_CREATE_PROFILE=true
      - DEFAULT_PRIVACY_MODE=linked
      # MPC Settings
      - DUO_NODE_URL=http://duo-node:3001
      - DUO_NODE_AUDIENCE_URL=http://duo-node:3001
      - SILENCE_ADMIN_TOKEN=dev-admin-token
      - SILENCE_NODE_URL=http://sigpair:8080
      - SILENCE_CLOUD_PUBLIC_KEY=020000000000000000000000000000000000000000000000000000000000000000
      - MPC_WEBHOOK_SECRET=dev-webhook-secret
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  # Duo Node service
  duo-node:
    build:
      context: ../interspace-duo-node
      dockerfile: Dockerfile
    container_name: interspace-duo-node-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DUO_SERVER_URL=http://sigpair:8080
      - DUO_NODE_AUDIENCE_URL=http://localhost:3001
      - LOG_LEVEL=debug
      - REQUEST_TIMEOUT_MS=30000
      - MAX_REQUEST_SIZE=1mb
      - SIGNATURE_SECRET=dev-signature-secret
      - SIGNATURE_REQUIRED=false
      - BACKEND_WEBHOOK_URL=http://app:3000/api/mpc/webhook
      - WEBHOOK_SECRET=dev-webhook-secret
    ports:
      - "3001:3001"
    depends_on:
      - sigpair
    volumes:
      - ../interspace-duo-node:/usr/src/app
      - /usr/src/app/node_modules

  # Silence Labs Duo Server (sigpair)
  sigpair-db:
    image: postgres:14-alpine
    container_name: interspace-sigpair-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: sigpair
      POSTGRES_PASSWORD: sigpair
      POSTGRES_DB: sigpair
    volumes:
      - sigpair-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sigpair"]
      interval: 10s
      timeout: 5s
      retries: 5

  sigpair:
    image: ghcr.io/silence-laboratories/duo-server:v2-latest
    container_name: interspace-sigpair-dev
    restart: unless-stopped
    environment:
      PGHOST: sigpair-db
      PGUSER: sigpair
      PGDATABASE: sigpair
      PGPASSWORD: sigpair
    ports:
      - "8080:8080"
    depends_on:
      sigpair-db:
        condition: service_healthy

volumes:
  postgres-dev-data:
  redis-dev-data:
  sigpair-db-data:

networks:
  default:
    name: interspace-dev-network