-- App Store Data Import
-- Generated from web3-apps-extended.json

-- Clear existing data
DELETE FROM "AppStoreApp";
DELETE FROM "AppStoreCategory";

-- Insert categories
INSERT INTO "AppStoreCategory" (id, name, slug, description, icon, position, "isActive", "createdAt", "updatedAt") VALUES
('cat_defi', 'DeFi', 'defi', 'Decentralized Finance applications', '💰', 1, true, NOW(), NOW()),
('cat_tools', 'Tools', 'tools', 'Utilities and productivity tools', '🛠️', 2, true, NOW(), NOW()),
('cat_gaming', 'Gaming', 'gaming', 'Web3 gaming and metaverse', '🎮', 3, true, NOW(), NOW()),
('cat_nft', 'NFT', 'nft', 'NFT marketplaces and tools', '🖼️', 4, true, NOW(), NOW()),
('cat_dao', 'DAO', 'dao', 'Decentralized Autonomous Organizations', '🏛️', 5, true, NOW(), NOW()),
('cat_social', 'Social', 'social', 'Social platforms and communities', '💬', 6, true, NOW(), NOW()),
('cat_bridge', 'Bridge', 'bridge', 'Cross-chain bridges', '🌉', 7, true, NOW(), NOW()),
('cat_gambling', 'Gambling', 'gambling', 'Gambling and prediction markets', '🎲', 8, true, NOW(), NOW()),
('cat_charity', 'Charity', 'charity', 'Charitable applications', '❤️', 9, true, NOW(), NOW()),
('cat_utilities', 'Utilities', 'utilities', 'Utility applications', '⚙️', 10, true, NOW(), NOW());

-- Insert apps
INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Uniswap', 'https://app.uniswap.org', 'https://cdn.brandfetch.io/idoYtBNi2C/w/800/h/868/theme/dark/idCjO30I1a.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Leading DEX for token swaps', 'Uniswap is the leading decentralized exchange protocol that allows users to swap ERC-20 tokens on Ethereum, Base, Arbitrum, Polygon, and other chains. Trusted by millions with the highest liquidity and best rates.', ARRAY['dex', 'swap', 'defi', 'ethereum'], 950, false, true, ARRAY['1'], ARRAY[]::text[], 'Uniswap Labs', '4.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'PancakeSwap', 'https://pancakeswap.finance', 'https://cdn.brandfetch.io/id-xm27CRB/w/512/h/512/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Leading BSC DEX with yield farming', 'PancakeSwap is the top decentralized exchange on BNB Smart Chain, offering trading, yield farming, staking, and lottery features. Trade, earn, and win crypto on the all-in-one multichain DEX.', ARRAY['dex', 'bsc', 'yield farming', 'defi'], 850, false, true, ARRAY['1', '56'], ARRAY[]::text[], 'PancakeSwap', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'OpenSea', 'https://opensea.io', 'https://assets.coingecko.com/coins/images/12271/large/512x512_Logo_no_chop.png', 'cat_nft', 'Leading NFT marketplace', 'OpenSea is a major NFT marketplace where you can discover, buy, sell, and trade NFTs. From art and music to domain names and virtual worlds, explore a vast collection of NFTs.', ARRAY['nft', 'marketplace', 'ethereum', 'polygon'], 900, false, true, ARRAY['1', '137'], ARRAY[]::text[], 'OpenSea', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Aave', 'https://app.aave.com', 'https://assets.coingecko.com/coins/images/12645/large/AAVE.png', 'cat_defi', 'Decentralized lending and borrowing protocol', 'Aave is a decentralized non-custodial liquidity market protocol where users can participate as depositors or borrowers. Earn interest on deposits and borrow assets at variable or stable rates.', ARRAY['lending', 'borrowing', 'defi', 'ethereum'], 820, false, true, ARRAY['1'], ARRAY[]::text[], 'Aave Labs', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Lido', 'https://lido.fi', 'https://cdn.brandfetch.io/idUE_o4e-p/w/820/h/217/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Liquid staking protocol', 'Lido is a liquid staking solution for Ethereum 2.0. Stake your ETH with no minimum amount and receive stETH while retaining liquidity for DeFi activities.', ARRAY['staking', 'ethereum', 'liquid', 'steth'], 840, false, true, ARRAY['1'], ARRAY[]::text[], 'Lido DAO', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Balancer', 'https://balancer.fi/pools', 'https://cdn.brandfetch.io/idwHnOTmw2/w/820/h/155/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Automated portfolio manager and DEX', 'Balancer is a decentralized automated market maker that allows users to create custom liquidity pools with multiple tokens and earn fees while maintaining exposure to their assets.', ARRAY['dex', 'amm', 'portfolio', 'liquidity'], 460, false, false, ARRAY['1'], ARRAY[]::text[], 'Balancer Labs', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Yearn Finance', 'https://yearn.fi/v3', 'https://cdn.brandfetch.io/id6rYjTMh6/w/640/h/640/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'DeFi yield optimization protocol', 'Yearn Finance is a decentralized ecosystem of aggregators for lending services such as Aave, Compound, and others. It automatically moves funds between protocols to maximize yields.', ARRAY['yield', 'farming', 'optimization', 'defi'], 420, false, false, ARRAY['1'], ARRAY[]::text[], 'Yearn Finance', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Velora', 'https://app.velora.xyz', 'https://cdn.brandfetch.io/iduqoSolxG/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Multi-chain DEX aggregator', 'Velora (formerly ParaSwap) aggregates decentralized exchanges and other DeFi services to offer users the best prices and liquidity across multiple blockchains.', ARRAY['aggregator', 'multichain', 'dex', 'swap'], 300, false, false, ARRAY['1'], ARRAY[]::text[], 'Velora', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Cowswap', 'https://swap.cow.fi', 'https://cdn.brandfetch.io/idLSPiiIbP/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'MEV protection trading protocol', 'CoW Swap is a DEX aggregator that protects traders from MEV by batching orders and finding better prices through coincidence of wants and DEX liquidity.', ARRAY['dex', 'mev protection', 'aggregator', 'ethereum'], 380, false, false, ARRAY['1'], ARRAY[]::text[], 'CoW Protocol', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'GMX', 'https://app.gmx.io', 'https://cdn.brandfetch.io/id27qr88zw/w/57/h/57/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Decentralized perpetual exchange', 'GMX is a decentralized spot and perpetual exchange that supports low swap fees and zero price impact trades. Trade with up to 50x leverage directly from your wallet.', ARRAY['perpetuals', 'leverage', 'trading', 'arbitrum'], 580, false, true, ARRAY['1', '42161'], ARRAY[]::text[], 'GMX DAO', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),

INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Spark', 'https://app.spark.fi', 'https://cdn.brandfetch.io/idI9wH6gDn/w/820/h/248/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Decentralized credit platform', 'Spark Protocol enables the generation of DAI and other stablecoins. Borrow against collateral and participate in governance of the protocol.', ARRAY['lending', 'dai', 'credit', 'governance'], 480, false, false, ARRAY['1'], ARRAY[]::text[], 'Spark Protocol', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Aura Finance', 'https://app.aura.finance', 'https://cdn.brandfetch.io/idNwEcOpon/w/64/h/64/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Balancer yield farming optimization', 'Aura Finance is a protocol built on top of Balancer that allows BAL and veBAL holders to maximize their yields through vlAURA tokenomics.', ARRAY['yield', 'balancer', 'optimization', 'voting'], 320, false, false, ARRAY['1'], ARRAY[]::text[], 'Aura Finance', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Aerodrome', 'https://aerodrome.finance', 'https://cdn.brandfetch.io/idWHg9Zf5A/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Base chain DEX and liquidity hub', 'Aerodrome is the central trading and liquidity marketplace on Base, featuring next-generation AMM and ve(3,3) tokenomics for sustainable yields.', ARRAY['dex', 'base', 've33', 'liquidity'], 340, false, false, ARRAY['1'], ARRAY[]::text[], 'Aerodrome Finance', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Frax', 'https://app.frax.finance', 'https://cdn.brandfetch.io/idD__GqZkx/w/57/h/57/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Fractional-algorithmic stablecoin protocol', 'Frax is the first fractional-algorithmic stablecoin system featuring FRAX (stablecoin), FXS (governance), and Frax Ether (liquid staking).', ARRAY['stablecoin', 'algorithmic', 'governance', 'staking'], 360, false, false, ARRAY['1'], ARRAY[]::text[], 'Frax Finance', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Syrup Finance', 'https://syrup.fi/lend', 'https://cdn.brandfetch.io/idPS3K0-pC/w/820/h/820/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Cross-chain lending protocol', 'Syrup Finance is a decentralized lending protocol that enables users to lend and borrow crypto assets across multiple blockchains.', ARRAY['lending', 'cross-chain', 'borrowing', 'yield'], 200, false, false, ARRAY['1'], ARRAY[]::text[], 'Syrup Finance', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Liquity', 'https://app.lqty.io', 'https://cdn.brandfetch.io/idGun0wZQA/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Zero-interest borrowing protocol', 'Liquity is a decentralized borrowing protocol that allows you to draw 0% interest loans against Ether used as collateral with LUSD stablecoin.', ARRAY['borrowing', 'zero interest', 'lusd', 'ethereum'], 280, false, false, ARRAY['1'], ARRAY[]::text[], 'Liquity AG', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'LlamaSwap', 'https://swap.defillama.com', 'https://cdn.brandfetch.io/idcbO3xegp/w/160/h/53/theme/light/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'DEX aggregator by DeFiLlama', 'LlamaSwap aggregates liquidity from major DEXs to provide users with the best swap rates across multiple chains with minimal slippage.', ARRAY['aggregator', 'dex', 'multichain', 'defillama'], 250, false, false, ARRAY['1'], ARRAY[]::text[], 'DeFiLlama', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Hitdex', 'https://www.hitdex.com', 'https://cdn.brandfetch.io/idvCUZmny-/w/192/h/192/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Advanced trading platform', 'HitDEX is a professional trading platform offering advanced features for cryptocurrency trading with institutional-grade tools and analytics.', ARRAY['trading', 'professional', 'analytics', 'dex'], 180, false, false, ARRAY['1'], ARRAY[]::text[], 'HitDEX', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Jumper Exchange', 'https://jumper.exchange', 'https://cdn.brandfetch.io/idPUz-VrHQ/w/57/h/57/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_bridge', 'Cross-chain bridge and swap', 'Jumper Exchange provides seamless cross-chain swaps and bridging services, connecting multiple blockchains for efficient asset transfers.', ARRAY['bridge', 'cross-chain', 'swap', 'multichain'], 320, false, false, ARRAY['1'], ARRAY[]::text[], 'Li.Fi', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Cabana (PoolTogether)', 'https://app.cabana.fi', 'https://cdn.brandfetch.io/idmb-jvDfQ/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_gambling', 'No-loss prize savings protocol', 'Cabana is the interface for PoolTogether, a no-loss prize game where you can win by saving. Deposit crypto to earn yield and have chances to win prizes.', ARRAY['savings', 'prizes', 'no-loss', 'yield'], 240, false, false, ARRAY['1'], ARRAY[]::text[], 'PoolTogether', '5.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),

INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'ETHFollow', 'https://www.ethfollow.xyz', 'https://cdn.brandfetch.io/idMO87zWK_/w/820/h/376/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_social', 'Ethereum-based social following', 'ETHFollow is a decentralized social platform that enables users to follow and connect with Ethereum addresses and their on-chain activities.', ARRAY['social', 'ethereum', 'following', 'onchain'], 150, false, false, ARRAY['1'], ARRAY[]::text[], 'ETHFollow', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Veil', 'https://www.veil.cash/app', 'https://cdn.brandfetch.io/idPSRvRDfm/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Privacy-focused cryptocurrency platform', 'Veil provides privacy-focused tools and services for cryptocurrency users, enabling anonymous transactions and enhanced privacy features.', ARRAY['privacy', 'anonymous', 'transactions', 'security'], 160, false, false, ARRAY['1'], ARRAY[]::text[], 'Veil', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Smol', 'https://smold.app', 'https://cdn.brandfetch.io/idmhSsWOIR/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Simple DeFi portfolio tracker', 'Smol is a minimalist DeFi portfolio tracker that helps users monitor their positions across various protocols with a clean, simple interface.', ARRAY['portfolio', 'tracker', 'defi', 'simple'], 140, false, false, ARRAY['1'], ARRAY[]::text[], 'Smol', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Revoke Cash', 'https://revoke.cash', 'https://cdn.brandfetch.io/idHz8grwuM/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Token approval management tool', 'Revoke.cash helps users manage and revoke token approvals to protect against smart contract risks and unauthorized spending of tokens.', ARRAY['security', 'approvals', 'revoke', 'protection'], 300, false, false, ARRAY['1'], ARRAY[]::text[], 'Revoke.cash', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Peanut', 'https://peanut.to', 'https://cdn.brandfetch.io/idcHSKYYLd/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Send crypto via links', 'Peanut Protocol allows users to send cryptocurrency to anyone via shareable links, making crypto transfers as easy as sending a message.', ARRAY['payments', 'links', 'send', 'crypto'], 220, false, false, ARRAY['1'], ARRAY[]::text[], 'Peanut Protocol', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Dump Services', 'https://dump.services', 'https://cdn.brandfetch.io/idKxhPUm-F/w/192/h/192/theme/light/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Crypto data and analytics platform', 'Dump Services provides comprehensive crypto market data, analytics, and tools for traders and investors to make informed decisions.', ARRAY['analytics', 'data', 'trading', 'tools'], 120, false, false, ARRAY['1'], ARRAY[]::text[], 'Dump Services', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Convex Finance', 'https://www.convexfinance.com', 'https://cdn.brandfetch.io/idwBaTaxSd/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Curve yield optimization platform', 'Convex Finance allows Curve liquidity providers to earn boosted CRV rewards and additional yield through simplified staking mechanisms.', ARRAY['curve', 'yield', 'optimization', 'crv'], 400, false, false, ARRAY['1'], ARRAY[]::text[], 'Convex Finance', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Polymarket', 'https://polymarket.com', 'https://cdn.brandfetch.io/idnft8znqj/w/223/h/223/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_gambling', 'Information markets platform', 'Polymarket is a decentralized information markets platform where users can trade on the outcome of future events and access crowd-sourced predictions.', ARRAY['prediction markets', 'betting', 'information', 'events'], 450, false, true, ARRAY['1'], ARRAY[]::text[], 'Polymarket', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Hyperliquid', 'https://app.hyperliquid.xyz', 'https://cdn.brandfetch.io/idGSMNVeGY/theme/dark/logo.svg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'High-performance perpetuals DEX', 'Hyperliquid is a performant on-chain perpetuals DEX with a fully on-chain order book, offering institutional-grade trading with decentralized infrastructure.', ARRAY['perpetuals', 'orderbook', 'high-performance', 'dex'], 380, false, true, ARRAY['1'], ARRAY[]::text[], 'Hyperliquid', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Aevo', 'https://www.aevo.xyz', 'https://cdn.brandfetch.io/idA8ZwkgIE/w/32/h/32/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Options and perpetuals trading', 'Aevo is a decentralized derivatives exchange focusing on options and perpetuals, built on Ethereum with high-performance order matching.', ARRAY['options', 'perpetuals', 'derivatives', 'ethereum'], 280, false, false, ARRAY['1'], ARRAY[]::text[], 'Aevo', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),

INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Rango Exchange', 'https://rango.exchange', 'https://cdn.brandfetch.io/idosqq83r6/w/256/h/256/theme/dark/icon.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_bridge', 'Cross-chain DEX aggregator', 'Rango Exchange is a cross-chain DEX aggregator that finds the best routes for swapping tokens across different blockchains with optimal prices.', ARRAY['cross-chain', 'aggregator', 'swap', 'bridge'], 200, false, false, ARRAY['1'], ARRAY[]::text[], 'Rango Exchange', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'DexScreener', 'https://dexscreener.com', 'https://cdn.brandfetch.io/idCmqPr_mu/w/180/h/180/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Real-time DEX trading data', 'DexScreener provides real-time trading data, charts, and analytics for tokens across multiple DEXs and blockchains.', ARRAY['analytics', 'dex', 'charts', 'trading'], 380, false, false, ARRAY['1'], ARRAY[]::text[], 'DexScreener', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Gas.zip', 'https://www.gas.zip', 'https://cdn.brandfetch.io/idd60CX8aD/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Cross-chain gas fee management', 'Gas.zip provides tools for managing and optimizing gas fees across different blockchains, helping users save on transaction costs.', ARRAY['gas', 'optimization', 'cross-chain', 'fees'], 160, false, false, ARRAY['1'], ARRAY[]::text[], 'Gas.zip', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Sideshift', 'https://sideshift.ai', 'https://cdn.brandfetch.io/idEcImrimn/w/400/h/400/theme/dark/icon.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_bridge', 'No-registration crypto exchange', 'SideShift AI is a cryptocurrency exchange service that requires no registration, allowing users to swap between different cryptocurrencies quickly and privately.', ARRAY['exchange', 'no-kyc', 'privacy', 'swap'], 220, false, false, ARRAY['1'], ARRAY[]::text[], 'SideShift AI', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'DeFiSaver', 'https://app.defisaver.com', 'https://cdn.brandfetch.io/id1SQOByUt/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'DeFi position management platform', 'DeFiSaver is a management platform for DeFi positions, offering automation, leverage management, and advanced features for protocols like MakerDAO and Aave.', ARRAY['management', 'automation', 'leverage', 'defi'], 260, false, false, ARRAY['1'], ARRAY[]::text[], 'DeFiSaver', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Definitive Fi', 'https://app.definitive.fi', 'https://cdn.brandfetch.io/idlhMnovwo/w/1361/h/155/theme/light/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'DeFi yield farming automation', 'Definitive Fi provides automated yield farming strategies and DeFi portfolio management tools to maximize returns across multiple protocols.', ARRAY['automation', 'yield farming', 'portfolio', 'optimization'], 140, false, false, ARRAY['1'], ARRAY[]::text[], 'Definitive Fi', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Endaoment', 'https://app.endaoment.org', 'https://cdn.brandfetch.io/idRqYgbk3m/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_charity', 'Crypto donation platform', 'Endaoment is a community-driven platform that facilitates cryptocurrency donations to nonprofits and charitable causes with full transparency.', ARRAY['charity', 'donations', 'nonprofit', 'transparency'], 100, false, false, ARRAY['1'], ARRAY[]::text[], 'Endaoment', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Catalog', 'https://catalog.works', 'https://cdn.brandfetch.io/idCbC54awX/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Creator economy platform', 'Catalog is a decentralized platform for creators to monetize their work through NFTs and direct fan support with built-in creator tools.', ARRAY['creator', 'nft', 'monetization', 'platform'], 120, false, false, ARRAY['1'], ARRAY[]::text[], 'Catalog', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Crosscurve', 'https://app.crosscurve.fi', 'https://app.crosscurve.fi/favicon.ico', 'cat_defi', 'Cross-chain yield farming', 'Crosscurve provides cross-chain yield farming opportunities and liquidity mining across multiple blockchains with optimized strategies.', ARRAY['cross-chain', 'yield farming', 'liquidity', 'optimization'], 110, false, false, ARRAY['1'], ARRAY[]::text[], 'Crosscurve', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Gains Trade', 'https://gains.trade', 'https://cdn.brandfetch.io/idxEDB9FTt/w/820/h/876/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Leveraged trading platform', 'Gains Trade offers leveraged trading for cryptocurrencies, forex, and stocks with decentralized infrastructure and competitive spreads.', ARRAY['leverage', 'trading', 'forex', 'stocks'], 200, false, false, ARRAY['1'], ARRAY[]::text[], 'Gains Network', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),

INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'LlamaPay', 'https://llamapay.io', 'https://cdn.brandfetch.io/id8ra3JLsn/w/400/h/400/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Money streaming protocol', 'LlamaPay enables continuous money streaming, allowing users to stream payments in real-time rather than traditional lump-sum transfers.', ARRAY['streaming', 'payments', 'continuous', 'salary'], 130, false, false, ARRAY['1'], ARRAY[]::text[], 'LlamaPay', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Superform', 'https://www.superform.xyz', 'https://cdn.brandfetch.io/idDhEUA3wl/w/400/h/400/theme/dark/icon.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Cross-chain yield infrastructure', 'Superform provides infrastructure for accessing yield opportunities across multiple chains through a unified interface and smart routing.', ARRAY['cross-chain', 'yield', 'infrastructure', 'routing'], 150, false, false, ARRAY['1'], ARRAY[]::text[], 'Superform Labs', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Courtyard', 'https://courtyard.io', 'https://cdn.brandfetch.io/idz3oLXqc4/w/180/h/180/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_nft', 'Physical collectibles NFT platform', 'Courtyard bridges physical collectibles with NFTs, allowing users to trade authenticated physical items as digital tokens with real-world backing.', ARRAY['physical', 'collectibles', 'nft', 'authentication'], 140, false, false, ARRAY['1'], ARRAY[]::text[], 'Courtyard', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Fileverse', 'https://ddocs.new', 'https://cdn.brandfetch.io/idzwCJ2oi9/w/370/h/370/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Decentralized document collaboration', 'Fileverse provides decentralized document creation and collaboration tools, enabling secure and private document sharing on blockchain infrastructure.', ARRAY['documents', 'collaboration', 'decentralized', 'privacy'], 90, false, false, ARRAY['1'], ARRAY[]::text[], 'Fileverse', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW());


-- Verify import
SELECT 
  c.name as category,
  COUNT(a.id) as app_count
FROM "AppStoreCategory" c
LEFT JOIN "AppStoreApp" a ON a."categoryId" = c.id
GROUP BY c.name
ORDER BY c.position;

-- Check specific apps
SELECT name, url FROM "AppStoreApp" WHERE name IN ('Fileverse', 'Uniswap', 'PancakeSwap');

-- Total count
SELECT COUNT(*) as total_apps FROM "AppStoreApp";
