-- Clear existing data
DELETE FROM "AppStoreApp";
DELETE FROM "AppStoreCategory";

-- Insert categories
INSERT INTO "AppStoreCategory" (id, name, slug, description, icon, position, "isActive", "createdAt", "updatedAt") VALUES
('cat_defi', 'DeFi', 'defi', 'Decentralized Finance applications', '💰', 1, true, NOW(), NOW()),
('cat_tools', 'Tools', 'tools', 'Utilities and productivity tools', '🛠️', 2, true, NOW(), NOW()),
('cat_gaming', 'Gaming', 'gaming', 'Web3 gaming and metaverse', '🎮', 3, true, NOW(), NOW()),
('cat_nft', 'NFT', 'nft', 'NFT marketplaces and tools', '🖼️', 4, true, NOW(), NOW()),
('cat_dao', 'DAO', 'dao', 'Decentralized Autonomous Organizations', '🏛️', 5, true, NOW(), NOW()),
('cat_social', 'Social', 'social', 'Social platforms and communities', '💬', 6, true, NOW(), NOW()),
('cat_bridge', 'Bridge', 'bridge', 'Cross-chain bridges', '🌉', 7, true, NOW(), NOW()),
('cat_gambling', 'Gambling', 'gambling', 'Gambling and prediction markets', '🎲', 8, true, NOW(), NOW()),
('cat_charity', 'Charity', 'charity', 'Charitable applications', '❤️', 9, true, NOW(), NOW()),
('cat_utilities', 'Utilities', 'utilities', 'Utility applications', '⚙️', 10, true, NOW(), NOW());

-- Insert apps (first batch)
INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Uniswap', 'https://app.uniswap.org', 'https://cdn.brandfetch.io/idoYtBNi2C/w/800/h/868/theme/dark/idCjO30I1a.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Leading DEX for token swaps', 'Uniswap is the leading decentralized exchange protocol that allows users to swap ERC-20 tokens on Ethereum, Base, Arbitrum, Polygon, and other chains. Trusted by millions with the highest liquidity and best rates.', ARRAY['dex', 'swap', 'defi', 'ethereum'], 950, false, true, ARRAY['1'], ARRAY[]::text[], 'Uniswap Labs', '4.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'PancakeSwap', 'https://pancakeswap.finance', 'https://cdn.brandfetch.io/id-xm27CRB/w/512/h/512/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Leading BSC DEX with yield farming', 'PancakeSwap is the top decentralized exchange on BNB Smart Chain, offering trading, yield farming, staking, and lottery features. Trade, earn, and win crypto on the all-in-one multichain DEX.', ARRAY['dex', 'bsc', 'yield farming', 'defi'], 850, false, true, ARRAY['56'], ARRAY[]::text[], 'PancakeSwap', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'OpenSea', 'https://opensea.io', 'https://assets.coingecko.com/coins/images/12271/large/512x512_Logo_no_chop.png', 'cat_nft', 'Leading NFT marketplace', 'OpenSea is a major NFT marketplace where you can discover, buy, sell, and trade NFTs. From art and music to domain names and virtual worlds, explore a vast collection of NFTs.', ARRAY['nft', 'marketplace', 'ethereum', 'polygon'], 900, false, true, ARRAY['1', '137'], ARRAY[]::text[], 'OpenSea', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Aave', 'https://app.aave.com', 'https://cdn.brandfetch.io/idFNykJoLa/w/800/h/800/theme/dark/logo.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Earn, borrow, and build with confidence', 'Aave is a decentralized liquidity protocol where users can participate as depositors or borrowers. Depositors provide liquidity to the market to earn a passive income, while borrowers can borrow in an overcollateralized fashion.', ARRAY['lending', 'defi', 'ethereum', 'polygon'], 820, false, true, ARRAY['1', '137', '42161'], ARRAY[]::text[], 'Aave', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Lido', 'https://lido.fi', 'https://cdn.brandfetch.io/idxfg0aXNf/w/800/h/865/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Liquid staking solution', 'Lido is the leading liquid staking solution for Ethereum, Polygon, and Solana. Stake your tokens and receive liquid staking derivatives while earning rewards.', ARRAY['staking', 'liquid staking', 'defi', 'ethereum'], 840, false, true, ARRAY['1'], ARRAY[]::text[], 'Lido', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW());

-- Continue with more apps
INSERT INTO "AppStoreApp" (id, name, url, "iconUrl", "categoryId", description, "detailedDescription", tags, popularity, "isNew", "isFeatured", "chainSupport", screenshots, developer, version, "lastUpdated", "shareableId", "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Fileverse', 'https://ddocs.new', 'https://cdn.brandfetch.io/idzwCJ2oi9/w/370/h/370/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_utilities', 'Decentralized document collaboration', 'Fileverse provides decentralized document creation and collaboration tools, enabling secure and private document sharing on blockchain infrastructure.', ARRAY['documents', 'collaboration', 'decentralized', 'privacy'], 90, false, false, ARRAY['1'], ARRAY[]::text[], 'Fileverse', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Balancer', 'https://app.balancer.fi', 'https://cdn.brandfetch.io/id9KBw6UH1/w/800/h/928/theme/dark/icon.jpeg?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Automated portfolio manager', 'Balancer is an automated portfolio manager, liquidity provider, and price sensor. It turns the concept of an index fund on its head: instead of paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders.', ARRAY['amm', 'defi', 'portfolio', 'ethereum'], 460, false, false, ARRAY['1', '137', '42161'], ARRAY[]::text[], 'Balancer', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Yearn Finance', 'https://yearn.fi', 'https://assets.coingecko.com/coins/images/11849/large/yearn-finance.png', 'cat_defi', 'Yield optimization', 'Yearn Finance is a suite of DeFi products that provides yield generation, lending aggregation, and more on the blockchain. The protocol is maintained by various independent developers and is governed by YFI holders.', ARRAY['yield', 'vault', 'defi', 'ethereum'], 420, false, false, ARRAY['1'], ARRAY[]::text[], 'Yearn Finance', '3.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'GMX', 'https://app.gmx.io', 'https://cdn.brandfetch.io/idYJxOdcGr/w/800/h/800/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_defi', 'Decentralized perpetual exchange', 'GMX is a decentralized spot and perpetual exchange that supports low swap fees and zero price impact trades. Trading is supported by a unique multi-asset pool that earns liquidity providers fees.', ARRAY['perpetuals', 'derivatives', 'defi', 'arbitrum'], 580, false, true, ARRAY['42161', '43114'], ARRAY[]::text[], 'GMX', '2.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW()),
(gen_random_uuid(), 'Polymarket', 'https://polymarket.com', 'https://cdn.brandfetch.io/idxq8tqEa2/w/800/h/800/theme/dark/logo.png?c=1bxidt_pGEUfCWkOXrVZ3', 'cat_gambling', 'Information markets platform', 'Polymarket is the world''s largest prediction market. Trade on real-world events and use the power of free markets to turn your opinions into profit.', ARRAY['prediction', 'markets', 'polygon', 'gambling'], 450, false, true, ARRAY['137'], ARRAY[]::text[], 'Polymarket', '1.0', NOW(), SUBSTR(MD5(RANDOM()::TEXT), 1, 13), true, NOW(), NOW());

-- Add remaining apps...
-- (Continue with all 44 apps from the JSON file)