steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/your-project-id/interspace-backend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/your-project-id/interspace-backend']
- name: 'google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'interspace-backend'
  - '--image'
  - 'gcr.io/your-project-id/interspace-backend'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
  - '--port'
  - '3000'
  - '--set-env-vars'
  - 'NODE_ENV=development,PORT=3000,API_VERSION=v1,DUO_NODE_URL=https://interspace-duo-node-621090718765.us-central1.run.app,DUO_NODE_AUDIENCE_URL=https://interspace-duo-node-621090718765.us-central1.run.app,CORS_ORIGINS=http://localhost:3000,http://localhost:19006,https://dev.interspace.fi,ORBY_INSTANCE_PRIVATE_API_KEY=c669420b-1cca-4a62-ab6c-a580fd06d575,ORBY_INSTANCE_PUBLIC_API_KEY=aae1a17a-6c09-4649-827e-fe5b49eb67b3,GOOGLE_CLIENT_ID=621090718765-ombc8j5rqibfao194c12o24e23q1q8ft.apps.googleusercontent.com,ORBY_PRIVATE_INSTANCE_URL=https://orby.dev.example.com,SILENCE_NODE_URL=http://silence-node.dev.example.com'
  - '--update-secrets'
  - 'DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,JWT_REFRESH_SECRET=JWT_REFRESH_SECRET:latest,ENCRYPTION_SECRET=ENCRYPTION_SECRET:latest,SILENCE_ADMIN_TOKEN=SILENCE_ADMIN_TOKEN:latest'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '10'
  - '--ingress'
  - 'all'