steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/interspace-backend-dev:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/interspace-backend-dev:latest'
    - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - '--all-tags'
    - 'gcr.io/$PROJECT_ID/interspace-backend-dev'

# Deploy to Cloud Run development service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'interspace-backend-dev'
    - '--image'
    - 'gcr.io/$PROJECT_ID/interspace-backend-dev:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--port'
    - '3000'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '5'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '300'
    - '--ingress'
    - 'all'
    - '--allow-unauthenticated'
    - '--vpc-connector'
    - 'projects/intersend/locations/us-central1/connectors/interspace-connector'
    - '--vpc-egress'
    - 'private-ranges-only'
    - '--set-env-vars'
    - 'NODE_ENV=development,PORT=3000,API_VERSION=v1'
    - '--set-secrets'
    - 'DATABASE_URL=interspace-dev-database-url:latest,JWT_SECRET=interspace-jwt-secret:latest,JWT_REFRESH_SECRET=interspace-jwt-refresh-secret:latest,ENCRYPTION_SECRET=interspace-encryption-secret:latest,SILENCE_ADMIN_TOKEN=interspace-silence-admin-token:latest,GOOGLE_CLIENT_ID=interspace-google-client-id:latest,APPLE_CLIENT_ID=interspace-apple-client-id:latest,ORBY_INSTANCE_PRIVATE_API_KEY=interspace-orby-private-key:latest,ORBY_INSTANCE_PUBLIC_API_KEY=interspace-orby-public-key:latest,REDIS_URL=interspace-dev-redis-url:latest,SENDGRID_API_KEY=interspace-dev-sendgrid-key:latest,SLACK_WEBHOOK_URL=interspace-dev-slack-webhook:latest'
    - '--update-env-vars'
    - 'DISABLE_MPC=false,BYPASS_LOGIN=false,SILENCE_NODE_URL=https://interspace-silence-node-dev-784862970473.us-central1.run.app,DUO_NODE_URL=https://interspace-duo-node-dev-784862970473.us-central1.run.app,DUO_NODE_AUDIENCE_URL=https://interspace-duo-node-dev-784862970473.us-central1.run.app,CORS_ORIGINS=http://localhost:3000;http://localhost:19006;https://dev.interspace.fi,ORBY_APP_NAME=interspace,ORBY_PRIVATE_INSTANCE_URL=https://api-rpc-dev.orblabs.xyz/c669420b-1cca-4a62-ab6c-a580fd06d575,FRONTEND_URL=https://dev.interspace.fi,DEFAULT_CHAIN_ID=11155111,SUPPORTED_CHAINS=11155111;10;137;42161;8453,RATE_LIMIT_WINDOW_MS=60000,RATE_LIMIT_MAX_REQUESTS=1000,REDIS_ENABLED=true,EMAIL_SERVICE=sendgrid,EMAIL_FROM=dev@interspace.fi,EMAIL_FROM_NAME=Interspace Dev,JWT_EXPIRES_IN=15m,JWT_REFRESH_EXPIRES_IN=7d'

# Run database migrations
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'execute'
    - 'interspace-db-migrate-dev'
    - '--region'
    - 'us-central1'
    - '--wait'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _SERVICE_NAME: 'interspace-backend-dev'
  _REGION: 'us-central1'
  _PROJECT_NUMBER: '784862970473'

timeout: '1200s'