steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/interspace-backend-prod:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/interspace-backend-prod:latest'
    - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - '--all-tags'
    - 'gcr.io/$PROJECT_ID/interspace-backend-prod'

# Deploy to Cloud Run production service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'interspace-backend-prod'
    - '--image'
    - 'gcr.io/$PROJECT_ID/interspace-backend-prod:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--port'
    - '3000'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '100'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '300'
    - '--ingress'
    - 'all'
    - '--allow-unauthenticated'
    - '--vpc-connector'
    - 'projects/intersend/locations/us-central1/connectors/interspace-connector'
    - '--vpc-egress'
    - 'private-ranges-only'
    - '--set-env-vars'
    - 'NODE_ENV=production,PORT=3000,API_VERSION=v1'
    - '--set-secrets'
    - 'DATABASE_URL=interspace-prod-database-url:latest,JWT_SECRET=interspace-prod-jwt-secret:latest,JWT_REFRESH_SECRET=interspace-prod-jwt-refresh-secret:latest,ENCRYPTION_SECRET=interspace-prod-encryption-secret:latest,SILENCE_ADMIN_TOKEN=interspace-prod-silence-admin-token:latest,GOOGLE_CLIENT_ID=interspace-prod-google-client-id:latest,APPLE_CLIENT_ID=interspace-prod-apple-client-id:latest,ORBY_INSTANCE_PRIVATE_API_KEY=interspace-prod-orby-private-key:latest,ORBY_INSTANCE_PUBLIC_API_KEY=interspace-prod-orby-public-key:latest,REDIS_URL=interspace-prod-redis-url:latest,SENDGRID_API_KEY=interspace-prod-sendgrid-key:latest,SLACK_WEBHOOK_URL=interspace-prod-slack-webhook:latest,DISCORD_WEBHOOK_URL=interspace-prod-discord-webhook:latest,PAGERDUTY_INTEGRATION_KEY=interspace-prod-pagerduty-key:latest'
    - '--update-env-vars'
    - 'DISABLE_MPC=false,BYPASS_LOGIN=false,SILENCE_NODE_URL=https://interspace-silence-node-prod-784862970473.us-central1.run.app,DUO_NODE_URL=https://interspace-duo-node-prod-784862970473.us-central1.run.app,DUO_NODE_AUDIENCE_URL=https://interspace-duo-node-prod-784862970473.us-central1.run.app,CORS_ORIGINS=https://app.interspace.fi;https://interspace.fi;capacitor://localhost;ionic://localhost,ORBY_APP_NAME=interspace,ORBY_PRIVATE_INSTANCE_URL=https://api-rpc-dev.orblabs.xyz/c669420b-1cca-4a62-ab6c-a580fd06d575,FRONTEND_URL=https://app.interspace.fi,DEFAULT_CHAIN_ID=1,SUPPORTED_CHAINS=1;10;137;42161;8453,RATE_LIMIT_WINDOW_MS=900000,RATE_LIMIT_MAX_REQUESTS=100,REDIS_ENABLED=true,EMAIL_SERVICE=sendgrid,EMAIL_FROM=noreply@interspace.fi,EMAIL_FROM_NAME=Interspace,JWT_EXPIRES_IN=15m,JWT_REFRESH_EXPIRES_IN=7d'

# Run database migrations
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'execute'
    - 'interspace-db-migrate-prod'
    - '--region'
    - 'us-central1'
    - '--wait'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _SERVICE_NAME: 'interspace-backend-prod'
  _REGION: 'us-central1'
  _PROJECT_NUMBER: '784862970473'

timeout: '1800s'